-- AlterTable
ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'ACTIVE',
ALTER COLUMN "role" SET DEFAULT 'USER',
ALTER COLUMN "is_banned" SET DEFAULT false,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
