FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY apps/web/package.json apps/web/package.json
COPY services/api-gateway/package.json services/api-gateway/package.json
COPY services/user-service/package.json services/user-service/package.json
COPY services/friendship-service/package.json services/friendship-service/package.json
COPY services/notification-service/package.json services/notification-service/package.json
COPY packages/events/package.json packages/events/package.json
COPY packages/shared-types/package.json packages/shared-types/package.json

RUN npm config set fetch-retries 5 \
    && npm config set fetch-retry-mintimeout 20000 \
    && npm config set fetch-retry-maxtimeout 120000 \
    && npm ci

COPY . .

ARG WORKSPACE
RUN npm run db:generate -w @chat-app/user-service
RUN npm run db:generate -w @chat-app/friendship-service
RUN npm run db:generate -w @chat-app/notification-service
RUN npm run build -w ${WORKSPACE}

FROM node:24-alpine AS runtime

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app /app

ARG WORKSPACE
ENV SERVICE_WORKSPACE=${WORKSPACE}

CMD ["sh", "-c", "npm run start -w ${SERVICE_WORKSPACE}"]
